apiVersion: v1
kind: ConfigMap
metadata:
  name: spinnaker-demo-config
  namespace: junk
data:
  NEW_FEATURE: "true"
  SECOND_FEATURE: "true"
  THIRD_FEATURE: "true"
  FROM_GIT: "true"

---

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: spinnaker-demo
  namespace: junk
  labels:
    source: demo
    stack: frontend
    app: spinnaker
spec:
  replicas: 2
  selector:
    matchLabels:
      source: demo
      app: spinnaker
  template:
    metadata:
      labels:
        source: demo
        app: spinnaker
    spec:
      containers:
      - name: primary
#        image: index.docker.io/lwander/spin-kub-v2-demo
        image: 498040579653.dkr.ecr.us-west-1.amazonaws.com/xtime/spin-kub-v2-demo:latest
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /
            port: 8000
        envFrom:
        - configMapRef:
            name: spinnaker-demo-config

---

kind: Service
apiVersion: v1
metadata:
  name: spinnaker-demo
  namespace: junk
spec:
  selector:
    source: demo
    app: spinnaker
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
